version: "3"
services:
  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    hostname: mongodb
    network_mode: host
    volumes:
      - ./data/database/configdb:/data/configdb
      - ./data/database/db:/data/db
    restart: unless-stopped
  smartdns:
    image: "runshine0819/smartdns:latest"
    container_name: smartdns
    hostname: smartdns
    command: ["/usr/sbin/smartdns","-f","-x","-u","udp://127.0.0.1:12345"]
    network_mode: host
    volumes:
      - ./data/smartdns:/etc/smartdns
    restart: unless-stopped
  smartdns-server:
    image: "runshine0819/smartdns-server:latest"
    container_name: smartdns-server
    hostname: smartdns-server
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - CAP_SYS_ADMIN
    command:  ["bash","-c","/dns_server.py --debug --socket=udp://127.0.0.1:12345 --extra=/opt/ --node_id=10.11.200.100 --dns=1.1.1.1 --mongodb=mongodb:///smartdns & /usr/lib/frr/docker-start"]
    volumes:
      - ./data/dnsmasq.d:/etc/dnsmasq.d
      - ./data/frr:/etc/frr
    restart: unless-stopped