name: build_docker

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push smartdns
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/s390x,linux/arm/v7,linux/arm/v6
          push: true
          tags: |
            runshine0819/smartdns:latest
            ghcr.io/runshine/smartdns:latest
          file: smartdns.dockerfile

      - name: Build and push smartdns-server
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/s390x,linux/arm/v7,linux/arm/v6
          push: true
          tags: |
            runshine0819/smartdns-server:latest
            ghcr.io/runshine/smartdns-server:latest
          file: smartdns-server.dockerfile
