name: build_x86_deb

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [ amd64, arm64 ]
    steps:
      - uses: actions/checkout@v4

      - name: Install czmq
        run: sudo apt-get install -y libczmq-dev

      - name: build-package
        run: cd package && ./build-pkg.sh --platform debian --arch x86-64

      - uses: actions/upload-artifact@v3
        with:
          name: smartdns-latest
          path: package/smartdns.*.deb
