name: build_x86_deb

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install czmq
        run: sudo apt-get install -y libczmq-dev

      - name: build-package
        run: cd package && ./build-pkg.sh --platform debian --arch x86-64

      - uses: actions/upload-artifact@v3
        with:
          name: smartdns-latest-x64
          path: package/smartdns.*.deb
