name: build_deb

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build-package
        run: cd package ;echo "ARCH is $(uname -a)"; if [ $(uname -m) == 'x86_64' ] ;then echo "build x86_64" && ./build-pkg.sh --platform debian --arch x86-64;fi; if [ $(uname -m) == 'aarch64' ] ;then echo "build aarch64" && ./build-pkg.sh --platform debian --arch aarch64;fi;

      - uses: actions/upload-artifact@v3
        with:
          name: smartdns-latest
          path: package/smartdns.*.deb

